### ISSUE TITLE
Control methods for `slideshow` mode

### ISSUE THREAD

**Issue by joseluisq** [joseluisq/slendr#57]
Future control methods for `slideshow` mode:

- [x] ~~Need to implement first the `slideshowAuto` option. #56~~
- [x] `play()` - start/resume the slideshow.
- [x] `pause()` - pause the slideshow.
- [x] `play` event - when slideshow is payed.
- [x] `pause` event - when slideshow is paused.

E.g.

``` js
const slider = Slendr({
  slideshow: true,
  slideshowAuto: true
})

slider.pause()
// or
slider.play()

```
